name: Deploy Development

on:
  push:
    branches: [ develop ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore backend/COSMOS.csproj
    
    - name: Build
      run: dotnet build backend/COSMOS.csproj --configuration Debug --no-restore
    
    - name: Publish
      run: dotnet publish backend/COSMOS.csproj -c Debug -o ./publish
    
    # Add steps to deploy to your development server